/*
 * This file is generated by jOOQ.
 */
package app.cta4j.jooq.tables;


import app.cta4j.jooq.Cta4j;
import app.cta4j.jooq.Keys;
import app.cta4j.jooq.tables.records.DirectionRecord;

import java.util.function.Function;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Function2;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Records;
import org.jooq.Row2;
import org.jooq.Schema;
import org.jooq.SelectField;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Direction extends TableImpl<DirectionRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>cta4j.direction</code>
     */
    public static final Direction DIRECTION = new Direction();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<DirectionRecord> getRecordType() {
        return DirectionRecord.class;
    }

    /**
     * The column <code>cta4j.direction.id</code>.
     */
    public final TableField<DirectionRecord, Integer> ID = createField(DSL.name("id"), SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>cta4j.direction.name</code>.
     */
    public final TableField<DirectionRecord, String> NAME = createField(DSL.name("name"), SQLDataType.CLOB.nullable(false), this, "");

    private Direction(Name alias, Table<DirectionRecord> aliased) {
        this(alias, aliased, null);
    }

    private Direction(Name alias, Table<DirectionRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>cta4j.direction</code> table reference
     */
    public Direction(String alias) {
        this(DSL.name(alias), DIRECTION);
    }

    /**
     * Create an aliased <code>cta4j.direction</code> table reference
     */
    public Direction(Name alias) {
        this(alias, DIRECTION);
    }

    /**
     * Create a <code>cta4j.direction</code> table reference
     */
    public Direction() {
        this(DSL.name("direction"), null);
    }

    public <O extends Record> Direction(Table<O> child, ForeignKey<O, DirectionRecord> key) {
        super(child, key, DIRECTION);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Cta4j.CTA4J;
    }

    @Override
    public Identity<DirectionRecord, Integer> getIdentity() {
        return (Identity<DirectionRecord, Integer>) super.getIdentity();
    }

    @Override
    public UniqueKey<DirectionRecord> getPrimaryKey() {
        return Keys.KEY_DIRECTION_PRIMARY;
    }

    @Override
    public Direction as(String alias) {
        return new Direction(DSL.name(alias), this);
    }

    @Override
    public Direction as(Name alias) {
        return new Direction(alias, this);
    }

    @Override
    public Direction as(Table<?> alias) {
        return new Direction(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Direction rename(String name) {
        return new Direction(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Direction rename(Name name) {
        return new Direction(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Direction rename(Table<?> name) {
        return new Direction(name.getQualifiedName(), null);
    }

    // -------------------------------------------------------------------------
    // Row2 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row2<Integer, String> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    public <U> SelectField<U> mapping(Function2<? super Integer, ? super String, ? extends U> from) {
        return convertFrom(Records.mapping(from));
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    public <U> SelectField<U> mapping(Class<U> toType, Function2<? super Integer, ? super String, ? extends U> from) {
        return convertFrom(toType, Records.mapping(from));
    }
}
