/*
 * This file is generated by jOOQ.
 */
package app.cta4j.jooq.tables;


import app.cta4j.jooq.Keys;
import app.cta4j.jooq.Public;
import app.cta4j.jooq.enums.Direction;
import app.cta4j.jooq.tables.records.RouteStopRecord;

import java.util.function.Function;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Function4;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Records;
import org.jooq.Row4;
import org.jooq.Schema;
import org.jooq.SelectField;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RouteStop extends TableImpl<RouteStopRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.route_stop</code>
     */
    public static final RouteStop ROUTE_STOP = new RouteStop();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<RouteStopRecord> getRecordType() {
        return RouteStopRecord.class;
    }

    /**
     * The column <code>public.route_stop.id</code>.
     */
    public final TableField<RouteStopRecord, Integer> ID = createField(DSL.name("id"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>public.route_stop.name</code>.
     */
    public final TableField<RouteStopRecord, String> NAME = createField(DSL.name("name"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>public.route_stop.route_id</code>.
     */
    public final TableField<RouteStopRecord, String> ROUTE_ID = createField(DSL.name("route_id"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>public.route_stop.direction</code>.
     */
    public final TableField<RouteStopRecord, Direction> DIRECTION = createField(DSL.name("direction"), SQLDataType.VARCHAR.nullable(false).asEnumDataType(Direction.class), this, "");

    private RouteStop(Name alias, Table<RouteStopRecord> aliased) {
        this(alias, aliased, null);
    }

    private RouteStop(Name alias, Table<RouteStopRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>public.route_stop</code> table reference
     */
    public RouteStop(String alias) {
        this(DSL.name(alias), ROUTE_STOP);
    }

    /**
     * Create an aliased <code>public.route_stop</code> table reference
     */
    public RouteStop(Name alias) {
        this(alias, ROUTE_STOP);
    }

    /**
     * Create a <code>public.route_stop</code> table reference
     */
    public RouteStop() {
        this(DSL.name("route_stop"), null);
    }

    public <O extends Record> RouteStop(Table<O> child, ForeignKey<O, RouteStopRecord> key) {
        super(child, key, ROUTE_STOP);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public UniqueKey<RouteStopRecord> getPrimaryKey() {
        return Keys.ROUTE_STOP_PKEY;
    }

    @Override
    public RouteStop as(String alias) {
        return new RouteStop(DSL.name(alias), this);
    }

    @Override
    public RouteStop as(Name alias) {
        return new RouteStop(alias, this);
    }

    @Override
    public RouteStop as(Table<?> alias) {
        return new RouteStop(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public RouteStop rename(String name) {
        return new RouteStop(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public RouteStop rename(Name name) {
        return new RouteStop(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public RouteStop rename(Table<?> name) {
        return new RouteStop(name.getQualifiedName(), null);
    }

    // -------------------------------------------------------------------------
    // Row4 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row4<Integer, String, String, Direction> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    public <U> SelectField<U> mapping(Function4<? super Integer, ? super String, ? super String, ? super Direction, ? extends U> from) {
        return convertFrom(Records.mapping(from));
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    public <U> SelectField<U> mapping(Class<U> toType, Function4<? super Integer, ? super String, ? super String, ? super Direction, ? extends U> from) {
        return convertFrom(toType, Records.mapping(from));
    }
}
