/*
 * This file is generated by jOOQ.
 */
package app.cta4j.jooq.tables;


import app.cta4j.jooq.Cta4j;
import app.cta4j.jooq.Keys;
import app.cta4j.jooq.tables.records.StopRecord;

import java.util.function.Function;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Function2;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Records;
import org.jooq.Row2;
import org.jooq.Schema;
import org.jooq.SelectField;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Stop extends TableImpl<StopRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>cta4j.stop</code>
     */
    public static final Stop STOP = new Stop();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<StopRecord> getRecordType() {
        return StopRecord.class;
    }

    /**
     * The column <code>cta4j.stop.id</code>.
     */
    public final TableField<StopRecord, Integer> ID = createField(DSL.name("id"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>cta4j.stop.name</code>.
     */
    public final TableField<StopRecord, String> NAME = createField(DSL.name("name"), SQLDataType.CLOB.nullable(false), this, "");

    private Stop(Name alias, Table<StopRecord> aliased) {
        this(alias, aliased, null);
    }

    private Stop(Name alias, Table<StopRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>cta4j.stop</code> table reference
     */
    public Stop(String alias) {
        this(DSL.name(alias), STOP);
    }

    /**
     * Create an aliased <code>cta4j.stop</code> table reference
     */
    public Stop(Name alias) {
        this(alias, STOP);
    }

    /**
     * Create a <code>cta4j.stop</code> table reference
     */
    public Stop() {
        this(DSL.name("stop"), null);
    }

    public <O extends Record> Stop(Table<O> child, ForeignKey<O, StopRecord> key) {
        super(child, key, STOP);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Cta4j.CTA4J;
    }

    @Override
    public UniqueKey<StopRecord> getPrimaryKey() {
        return Keys.KEY_STOP_PRIMARY;
    }

    @Override
    public Stop as(String alias) {
        return new Stop(DSL.name(alias), this);
    }

    @Override
    public Stop as(Name alias) {
        return new Stop(alias, this);
    }

    @Override
    public Stop as(Table<?> alias) {
        return new Stop(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Stop rename(String name) {
        return new Stop(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Stop rename(Name name) {
        return new Stop(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Stop rename(Table<?> name) {
        return new Stop(name.getQualifiedName(), null);
    }

    // -------------------------------------------------------------------------
    // Row2 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row2<Integer, String> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    public <U> SelectField<U> mapping(Function2<? super Integer, ? super String, ? extends U> from) {
        return convertFrom(Records.mapping(from));
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    public <U> SelectField<U> mapping(Class<U> toType, Function2<? super Integer, ? super String, ? extends U> from) {
        return convertFrom(toType, Records.mapping(from));
    }
}
