/*
 * This file is generated by jOOQ.
 */
package app.cta4j.jooq.tables.records;


import app.cta4j.jooq.tables.RouteStop;

import org.jooq.Field;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RouteStopRecord extends UpdatableRecordImpl<RouteStopRecord> implements Record3<String, Integer, Integer> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>cta4j.route_stop.route_id</code>.
     */
    public void setRouteId(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>cta4j.route_stop.route_id</code>.
     */
    public String getRouteId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>cta4j.route_stop.direction_id</code>.
     */
    public void setDirectionId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>cta4j.route_stop.direction_id</code>.
     */
    public Integer getDirectionId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>cta4j.route_stop.stop_id</code>.
     */
    public void setStopId(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>cta4j.route_stop.stop_id</code>.
     */
    public Integer getStopId() {
        return (Integer) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record3<String, Integer, Integer> key() {
        return (Record3) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row3<String, Integer, Integer> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    @Override
    public Row3<String, Integer, Integer> valuesRow() {
        return (Row3) super.valuesRow();
    }

    @Override
    public Field<String> field1() {
        return RouteStop.ROUTE_STOP.ROUTE_ID;
    }

    @Override
    public Field<Integer> field2() {
        return RouteStop.ROUTE_STOP.DIRECTION_ID;
    }

    @Override
    public Field<Integer> field3() {
        return RouteStop.ROUTE_STOP.STOP_ID;
    }

    @Override
    public String component1() {
        return getRouteId();
    }

    @Override
    public Integer component2() {
        return getDirectionId();
    }

    @Override
    public Integer component3() {
        return getStopId();
    }

    @Override
    public String value1() {
        return getRouteId();
    }

    @Override
    public Integer value2() {
        return getDirectionId();
    }

    @Override
    public Integer value3() {
        return getStopId();
    }

    @Override
    public RouteStopRecord value1(String value) {
        setRouteId(value);
        return this;
    }

    @Override
    public RouteStopRecord value2(Integer value) {
        setDirectionId(value);
        return this;
    }

    @Override
    public RouteStopRecord value3(Integer value) {
        setStopId(value);
        return this;
    }

    @Override
    public RouteStopRecord values(String value1, Integer value2, Integer value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached RouteStopRecord
     */
    public RouteStopRecord() {
        super(RouteStop.ROUTE_STOP);
    }

    /**
     * Create a detached, initialised RouteStopRecord
     */
    public RouteStopRecord(String routeId, Integer directionId, Integer stopId) {
        super(RouteStop.ROUTE_STOP);

        setRouteId(routeId);
        setDirectionId(directionId);
        setStopId(stopId);
        resetChangedOnNotNull();
    }
}
