/*
 * This file is generated by jOOQ.
 */
package app.cta4j.jooq.tables.records;


import app.cta4j.jooq.tables.Stop;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class StopRecord extends UpdatableRecordImpl<StopRecord> implements Record2<Integer, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>cta4j.stop.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>cta4j.stop.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>cta4j.stop.name</code>.
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>cta4j.stop.name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row2<Integer, String> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    @Override
    public Row2<Integer, String> valuesRow() {
        return (Row2) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return Stop.STOP.ID;
    }

    @Override
    public Field<String> field2() {
        return Stop.STOP.NAME;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getName();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getName();
    }

    @Override
    public StopRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public StopRecord value2(String value) {
        setName(value);
        return this;
    }

    @Override
    public StopRecord values(Integer value1, String value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached StopRecord
     */
    public StopRecord() {
        super(Stop.STOP);
    }

    /**
     * Create a detached, initialised StopRecord
     */
    public StopRecord(Integer id, String name) {
        super(Stop.STOP);

        setId(id);
        setName(name);
        resetChangedOnNotNull();
    }
}
