/*
 * This file is generated by jOOQ.
 */
package app.cta4j.jooq;


import app.cta4j.jooq.tables.Route;
import app.cta4j.jooq.tables.RouteDirection;
import app.cta4j.jooq.tables.RouteStop;
import app.cta4j.jooq.tables.Station;
import app.cta4j.jooq.tables.records.RouteDirectionRecord;
import app.cta4j.jooq.tables.records.RouteRecord;
import app.cta4j.jooq.tables.records.RouteStopRecord;
import app.cta4j.jooq.tables.records.StationRecord;

import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables in
 * public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<RouteRecord> ROUTE_PKEY = Internal.createUniqueKey(Route.ROUTE, DSL.name("route_pkey"), new TableField[] { Route.ROUTE.ID }, true);
    public static final UniqueKey<RouteDirectionRecord> ROUTE_DIRECTION_PKEY = Internal.createUniqueKey(RouteDirection.ROUTE_DIRECTION, DSL.name("route_direction_pkey"), new TableField[] { RouteDirection.ROUTE_DIRECTION.ROUTE_ID, RouteDirection.ROUTE_DIRECTION.DIRECTION }, true);
    public static final UniqueKey<RouteStopRecord> ROUTE_STOP_PKEY = Internal.createUniqueKey(RouteStop.ROUTE_STOP, DSL.name("route_stop_pkey"), new TableField[] { RouteStop.ROUTE_STOP.ID }, true);
    public static final UniqueKey<StationRecord> STATION_PKEY = Internal.createUniqueKey(Station.STATION, DSL.name("station_pkey"), new TableField[] { Station.STATION.ID }, true);
}
