/*
 * This file is generated by jOOQ.
 */
package app.cta4j.jooq;


import app.cta4j.jooq.tables.Direction;
import app.cta4j.jooq.tables.Route;
import app.cta4j.jooq.tables.RouteDirection;
import app.cta4j.jooq.tables.RouteStop;
import app.cta4j.jooq.tables.Station;
import app.cta4j.jooq.tables.Stop;


/**
 * Convenience access to all tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.direction</code>.
     */
    public static final Direction DIRECTION = Direction.DIRECTION;

    /**
     * The table <code>public.route</code>.
     */
    public static final Route ROUTE = Route.ROUTE;

    /**
     * The table <code>public.route_direction</code>.
     */
    public static final RouteDirection ROUTE_DIRECTION = RouteDirection.ROUTE_DIRECTION;

    /**
     * The table <code>public.route_stop</code>.
     */
    public static final RouteStop ROUTE_STOP = RouteStop.ROUTE_STOP;

    /**
     * The table <code>public.station</code>.
     */
    public static final Station STATION = Station.STATION;

    /**
     * The table <code>public.stop</code>.
     */
    public static final Stop STOP = Stop.STOP;
}
