name: CTA Bus Service PR CI
on:
  pull_request_target:
    branches: [ "main" ]
jobs:
  build:
    name: Build with Maven
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v3
      - name: Setup JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '21'
      - name: Build with Maven
        env:
          BUS_API_KEY: ${{ secrets.BUS_API_KEY }}
          FRONT_END_URL: ${{ secrets.FRONT_END_URL }}
          ROLLBAR_ACCESS_TOKEN: ${{ secrets.ROLLBAR_ACCESS_TOKEN }}
          ROLLBAR_ENVIRONMENT: ${{ secrets.ROLLBAR_ENVIRONMENT }}
          JDBC_DRIVER: ${{ secrets.JDBC_DRIVER }}
          JDBC_PASSWORD: ${{ secrets.JDBC_PASSWORD }}
          JDBC_URL: ${{ secrets.JDBC_URL }}
          JDBC_USERNAME: ${{ secrets.JDBC_USERNAME }}
          JOOQ_SQL_DIALECT: ${{ secrets.JOOQ_SQL_DIALECT }}
        run: mvn -B package --file pom.xml