name: CTA Bus Service CI
on:
  push:
    branches: [ "main" ]
jobs:
  build:
    name: Build with Maven
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v3
      - name: Setup JDK 20
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '20'
      - name: Build with Maven
        env:
          BUS_API_KEY: ${{ secrets.BUS_API_KEY }}
          FRONT_END_URL: ${{ secrets.FRONT_END_URL }}
          ROLLBAR_ACCESS_TOKEN: ${{ secrets.ROLLBAR_ACCESS_TOKEN }}
          ROLLBAR_ENVIRONMENT: ${{ secrets.ROLLBAR_ENVIRONMENT }}
        run: mvn -B package --file pom.xml